// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService handles AI chat and analysis features.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChatWithAI(message: string): $CancellablePromise<$models.ChatResponse | null> {
    return $Call.ByID(1082724026, message).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClearChatHistory(): $CancellablePromise<void> {
    return $Call.ByID(3032116087);
}

export function DecomposeTask(taskId: string): $CancellablePromise<string> {
    return $Call.ByID(2936384602, taskId);
}

export function GenerateWeeklyReport(): $CancellablePromise<string> {
    return $Call.ByID(3661357588);
}

export function GetDailySummary(): $CancellablePromise<string> {
    return $Call.ByID(968499405);
}

export function PrioritizeTasks(projectId: string): $CancellablePromise<string> {
    return $Call.ByID(2536206107, projectId);
}

/**
 * ReloadClient re-initialises the AI client from stored config.
 */
export function ReloadClient(): $CancellablePromise<void> {
    return $Call.ByID(2290836672);
}

export function SmartSuggestTasks(projectId: string): $CancellablePromise<string> {
    return $Call.ByID(1202614731, projectId);
}

export function TestAIConnection(): $CancellablePromise<void> {
    return $Call.ByID(2655471488);
}

// Private type creation functions
const $$createType0 = $models.ChatResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
