// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService handles application configuration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAIConfig(): $CancellablePromise<$models.AIConfig | null> {
    return $Call.ByID(1514248118).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(3594034821);
}

export function SaveAIConfig(apiKey: string, baseURL: string, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(199356151, apiKey, baseURL, modelName);
}

export function SaveAPIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(4111962512, key);
}

export function TestAIConnection(): $CancellablePromise<void> {
    return $Call.ByID(931474788);
}

// Private type creation functions
const $$createType0 = $models.AIConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
