// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIConfig holds the AI configuration.
 */
export class AIConfig {
    "apiKey": string;
    "baseURL": string;
    "model": string;

    /** Creates a new AIConfig instance. */
    constructor($$source: Partial<AIConfig> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConfig($$parsedSource as Partial<AIConfig>);
    }
}

/**
 * ChatResponse is returned from ChatWithAI to the frontend.
 */
export class ChatResponse {
    "text": string;
    "toolCalls": ToolCallResult[];

    /** Creates a new ChatResponse instance. */
    constructor($$source: Partial<ChatResponse> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("toolCalls" in $$source)) {
            this["toolCalls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCalls" in $$parsedSource) {
            $$parsedSource["toolCalls"] = $$createField1_0($$parsedSource["toolCalls"]);
        }
        return new ChatResponse($$parsedSource as Partial<ChatResponse>);
    }
}

/**
 * ToolCallResult represents the outcome of a single AI tool call.
 */
export class ToolCallResult {
    "action": string;
    "success": boolean;
    "message": string;

    /** Creates a new ToolCallResult instance. */
    constructor($$source: Partial<ToolCallResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallResult($$parsedSource as Partial<ToolCallResult>);
    }
}

// Private type creation functions
const $$createType0 = ToolCallResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
