// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService handles project CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

export function CreateProject(name: string, description: string, color: string): $CancellablePromise<model$0.Project | null> {
    return $Call.ByID(2778051416, name, description, color).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(27462813, id);
}

export function GetProjects(): $CancellablePromise<model$0.Project[]> {
    return $Call.ByID(923151623).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateProject(id: string, name: string, description: string, color: string): $CancellablePromise<void> {
    return $Call.ByID(3507567083, id, name, description, color);
}

// Private type creation functions
const $$createType0 = model$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
