// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService handles task CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

export function CreateTask(title: string, projectId: string, description: string, priority: number, dueDate: string): $CancellablePromise<model$0.Task | null> {
    return $Call.ByID(1827820032, title, projectId, description, priority, dueDate).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3347907499, id);
}

export function GetAllTasks(): $CancellablePromise<model$0.Task[]> {
    return $Call.ByID(3488755352).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetTasksByProject(projectId: string): $CancellablePromise<model$0.Task[]> {
    return $Call.ByID(106418095, projectId).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetTodayTasks(): $CancellablePromise<model$0.Task[]> {
    return $Call.ByID(230760254).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateTask(id: string, title: string, projectId: string, description: string, status: string, priority: number, dueDate: string): $CancellablePromise<void> {
    return $Call.ByID(320897429, id, title, projectId, description, status, priority, dueDate);
}

// Private type creation functions
const $$createType0 = model$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
