// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClaudeClient wraps the Claude API via the official SDK.
 */
export class ClaudeClient {

    /** Creates a new ClaudeClient instance. */
    constructor($$source: Partial<ClaudeClient> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeClient instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeClient {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeClient($$parsedSource as Partial<ClaudeClient>);
    }
}
